version: '3.8'

services:
  postgres:
    image: 'docker.io/library/postgres:17-alpine'
    container_name: postgres
    environment:
      POSTGRES_DB: timedeposit
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/timedeposit
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
